apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    service: bhasha-identity
  ports:
    - name: http
      protocol: TCP
      port: 5004 # exposed port (access website)
      targetPort: 80 # container port of pod hosting website
    - name: https
      protocol: TCP
      port: 5005 # exposed port (access website)
      targetPort: 443 # container port of pod hosting website