apiVersion: v1
kind: Service
metadata:
  name: author-api-service
spec:
  type: LoadBalancer
  selector:
    service: bhasha-author-api
  ports:
    - protocol: TCP
      port: 5000 # exposed port (access website)
      targetPort: 80 # container port of pod hosting website
