kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-volume
 labels:
  type: mongo-volume
spec:
 storageClassName: manual
 capacity:
  storage: 2Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo"
