apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhasha
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bhasha
  template:
    metadata:
      labels:
        app: bhasha
        service: bhasha
    spec:
      containers:
        - name: bhasha
          image: bhasha:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: bhasha-config-volume
              mountPath: /app/config
          env:
            - name: ASPNETCORE_Database__User
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-user
            - name: ASPNETCORE_Database__Password
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-password
      volumes:
      - name: bhasha-config-volume
        configMap:
          name: bhasha-config