apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    service: web
  ports:
    - port: 80 # container port of pod hosting website
      targetPort: 80 # exposed port (access website)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        app: web
        service: web
    spec:
      containers:
        - name: bhasha
          image: bhasha:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_MongoUser
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-user
            - name: ASPNETCORE_MongoPassword
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-password          
            - name: ASPNETCORE_MongoHost
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: hostname
