apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhasha
  labels:
    app: bhasha
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bhasha
  template:
    metadata:
      labels:
        app: bhasha
        service: bhasha
    spec:
      containers:
        - name: bhasha
          image: bhasha:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_MongoDB
              value: mongodb://admin:password@mongodb-0.db.default.svc.cluster.local:27017
---
apiVersion: v1
kind: Service
metadata:
  name: bhasha
  labels:
    app: bhasha
    service: bhasha
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: bhasha