apiVersion: v1
kind: Service
metadata:
  name: student-api-service
spec:
  type: LoadBalancer
  selector:
    service: bhasha-student-api
  ports:
    - port: 5002 # exposed port (access website)
      targetPort: 80 # container port of pod hosting website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhasha-student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bhasha-student-api
  template:
    metadata:
      labels:
        app: bhasha-student-api
        service: bhasha-student-api
    spec:
      containers:
        - name: bhasha-student-api
          image: bhasha-student-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_Database__User
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-user
            - name: ASPNETCORE_Database__Password
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-password          
            - name: ASPNETCORE_Database__Hostname
              value: mongodb-0.db.default.svc.cluster.local:27017
