name: Bhasha

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: npm install
      working-directory: Bhasha.Web.Client

    - name: NPM Test
      run: npm test
      working-directory: Bhasha.Web.Client

    - name: NPM Build
      run: npm run build
      working-directory: Bhasha.Web.Client

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: .NET Restore
      run: dotnet restore

    - name: .NET Build
      run: dotnet build --configuration Release --no-restore

    - name: .NET Test
      run: dotnet test --no-restore --verbosity normal

    - name: .NET Pack
      run: dotnet pack -c Release -o . --no-build  
